package daun.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_formatSTATUS extends EnumerationDescriptorBase {

  public EnumerationDescriptor_formatSTATUS() {
    super(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10617aL, "formatSTATUS", "r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954362");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HADIR_0 = new EnumerationDescriptor.MemberDescriptor("HADIR", "HADIR", 0x13bb48ea8c10617cL, "r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954364");
  private final EnumerationDescriptor.MemberDescriptor myMember_IZIN_0 = new EnumerationDescriptor.MemberDescriptor("IZIN", "IZIN", 0x13bb48ea8c10617bL, "r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954363");
  private final EnumerationDescriptor.MemberDescriptor myMember_SAKIT_0 = new EnumerationDescriptor.MemberDescriptor("SAKIT", "SAKIT", 0x13bb48ea8c10617dL, "r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954365");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALFA_0 = new EnumerationDescriptor.MemberDescriptor("ALFA", "ALFA", 0x13bb48ea8c10617eL, "r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954366");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10617aL, 0x13bb48ea8c10617cL, 0x13bb48ea8c10617bL, 0x13bb48ea8c10617dL, 0x13bb48ea8c10617eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_HADIR_0, myMember_IZIN_0, myMember_SAKIT_0, myMember_ALFA_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HADIR":
        return myMember_HADIR_0;
      case "IZIN":
        return myMember_IZIN_0;
      case "SAKIT":
        return myMember_SAKIT_0;
      case "ALFA":
        return myMember_ALFA_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
