package daun.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Absensi = 0;
  public static final int Data_Matkul = 1;
  public static final int Matkul = 2;
  public static final int Program = 3;
  public static final int Status = 4;
  public static final int Status_Data = 5;
  public static final int mahasiswa = 6;
  public static final int matkul_attribute = 7;
  public static final int rekap_jumlah = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L);
    builder.put(0x74c9b692ac2e0e64L, Absensi);
    builder.put(0x13bb48ea8c10616aL, Data_Matkul);
    builder.put(0x13bb48ea8c106163L, Matkul);
    builder.put(0x13bb48ea8c106155L, Program);
    builder.put(0x13bb48ea8c106165L, Status);
    builder.put(0x13bb48ea8c106166L, Status_Data);
    builder.put(0x13bb48ea8c10615bL, mahasiswa);
    builder.put(0x13bb48ea8c106164L, matkul_attribute);
    builder.put(0x13bb48ea8c10615cL, rekap_jumlah);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
