package daun.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAbsensi = createDescriptorForAbsensi();
  /*package*/ final ConceptDescriptor myConceptData_Matkul = createDescriptorForData_Matkul();
  /*package*/ final ConceptDescriptor myConceptMatkul = createDescriptorForMatkul();
  /*package*/ final ConceptDescriptor myConceptProgram = createDescriptorForProgram();
  /*package*/ final ConceptDescriptor myConceptStatus = createDescriptorForStatus();
  /*package*/ final ConceptDescriptor myConceptStatus_Data = createDescriptorForStatus_Data();
  /*package*/ final ConceptDescriptor myConceptmahasiswa = createDescriptorFormahasiswa();
  /*package*/ final ConceptDescriptor myConceptmatkul_attribute = createDescriptorFormatkul_attribute();
  /*package*/ final ConceptDescriptor myConceptrekap_jumlah = createDescriptorForrekap_jumlah();
  /*package*/ final EnumerationDescriptor myEnumerationUNIT = new EnumerationDescriptor_UNIT();
  /*package*/ final EnumerationDescriptor myEnumerationformatSTATUS = new EnumerationDescriptor_formatSTATUS();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAbsensi, myConceptData_Matkul, myConceptMatkul, myConceptProgram, myConceptStatus, myConceptStatus_Data, myConceptmahasiswa, myConceptmatkul_attribute, myConceptrekap_jumlah);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Absensi:
        return myConceptAbsensi;
      case LanguageConceptSwitch.Data_Matkul:
        return myConceptData_Matkul;
      case LanguageConceptSwitch.Matkul:
        return myConceptMatkul;
      case LanguageConceptSwitch.Program:
        return myConceptProgram;
      case LanguageConceptSwitch.Status:
        return myConceptStatus;
      case LanguageConceptSwitch.Status_Data:
        return myConceptStatus_Data;
      case LanguageConceptSwitch.mahasiswa:
        return myConceptmahasiswa;
      case LanguageConceptSwitch.matkul_attribute:
        return myConceptmatkul_attribute;
      case LanguageConceptSwitch.rekap_jumlah:
        return myConceptrekap_jumlah;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationUNIT, myEnumerationformatSTATUS);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAbsensi() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "Absensi", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x74c9b692ac2e0e64L);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/8415458119788662372");
    b.version(3);
    b.property("id", 0x13bb48ea8c10615dL).type(PrimitiveTypeId.STRING).origin("1421810279574954333").done();
    b.aggregate("Mahasiswa", 0x13bb48ea8c10615eL).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615bL).optional(false).ordered(true).multiple(true).origin("1421810279574954334").done();
    b.aggregate("mata_kuliah", 0x13bb48ea8c109969L).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106163L).optional(false).ordered(true).multiple(true).origin("1421810279574968681").done();
    b.aggregate("status", 0x13bb48ea8c10996aL).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106165L).optional(false).ordered(true).multiple(true).origin("1421810279574968682").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForData_Matkul() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "Data_Matkul", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10616aL);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954346");
    b.version(3);
    b.property("nama", 0x13bb48ea8c10616cL).type(PrimitiveTypeId.STRING).origin("1421810279574954348").done();
    b.aggregate("attr_list_matkul", 0x13bb48ea8c10616dL).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106164L).optional(false).ordered(true).multiple(true).origin("1421810279574954349").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMatkul() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "Matkul", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106163L);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954339");
    b.version(3);
    b.aggregate("list_matkul", 0x13bb48ea8c106169L).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10616aL).optional(false).ordered(true).multiple(true).origin("1421810279574954345").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "Program", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106155L);
    b.class_(false, false, true);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954325");
    b.version(3);
    b.aggregate("absensi_list", 0x13bb48ea8c106158L).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x74c9b692ac2e0e64L).optional(false).ordered(true).multiple(true).origin("1421810279574954328").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatus() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "Status", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106165L);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954341");
    b.version(3);
    b.aggregate("list_data_status", 0x13bb48ea8c106170L).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106166L).optional(false).ordered(true).multiple(true).origin("1421810279574954352").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatus_Data() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "Status_Data", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106166L);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954342");
    b.version(3);
    b.property("nama", 0x13bb48ea8c106171L).type(PrimitiveTypeId.STRING).origin("1421810279574954353").done();
    b.property("status", 0x13bb48ea8c106172L).type(MetaIdFactory.dataTypeId(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10617aL)).origin("1421810279574954354").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFormahasiswa() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "mahasiswa", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615bL);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954331");
    b.version(3);
    b.aggregate("list_rekap", 0x13bb48ea8c10615fL).target(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615cL).optional(false).ordered(true).multiple(true).origin("1421810279574954335").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFormatkul_attribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "matkul_attribute", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106164L);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954340");
    b.version(3);
    b.property("sks", 0x13bb48ea8c10616eL).type(PrimitiveTypeId.INTEGER).origin("1421810279574954350").done();
    b.property("jadwal", 0x13bb48ea8c10616fL).type(PrimitiveTypeId.STRING).origin("1421810279574954351").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForrekap_jumlah() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("daun", "rekap_jumlah", 0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615cL);
    b.class_(false, false, false);
    b.origin("r:81b43fd3-33f7-4873-a178-a8e9d6193b1e(daun.structure)/1421810279574954332");
    b.version(3);
    b.property("nama", 0x13bb48ea8c106160L).type(PrimitiveTypeId.STRING).origin("1421810279574954336").done();
    b.property("jumlah", 0x13bb48ea8c106161L).type(PrimitiveTypeId.INTEGER).origin("1421810279574954337").done();
    b.property("unit", 0x13bb48ea8c106162L).type(MetaIdFactory.dataTypeId(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10617fL)).origin("1421810279574954338").done();
    return b.create();
  }
}
