package daun.sandbox;

/*Generated by MPS */


public class ProgramTemplate {
  public static void main(String[] args) {
    System.out.println("===== DAFTAR ABSENSI =====");

    System.out.println("--------------");
    System.out.println("Absensi ID: " + "12345");
    System.out.println("Mahasiswa: ");
    System.out.println("NIM: " + "11111");
    System.out.println("Nama: " + "sadasjd");
    System.out.println("ID: " + "12312");
    System.out.println("Mata Kuliah: " + "[Lorg.jetbrains.mps.openapi.model.SNode;@440e192b");
    System.out.println("Status: " + "[Lorg.jetbrains.mps.openapi.model.SNode;@655bbfed");
  }
}
