package daun.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Absensi_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Absensi_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Absensi$6x, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Absensi$6x = MetaAdapterFactory.getConcept(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x74c9b692ac2e0e64L, "daun.structure.Absensi");
  }
}
