package daun.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Data_Matkul_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Data_Matkul_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Data_Matkul$2, initContext);
    record(new Nama_PD(this));
  }

  /*package*/ static final class Nama_PD extends BasePropertyConstraintsDescriptor {
    public Nama_PD(ConstraintsDescriptor container) {
      super(PROPS.nama$WPyM, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8507255052449860219"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return propertyValue != null && propertyValue != "";
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Data_Matkul$2 = MetaAdapterFactory.getConcept(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10616aL, "daun.structure.Data_Matkul");
  }

  private static final class PROPS {
    /*package*/ static final SProperty nama$WPyM = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10616aL, 0x13bb48ea8c10616cL, "nama");
  }
}
