package daun.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class matkul_attribute_Constraints extends BaseConstraintsDescriptor {
  /*package*/ matkul_attribute_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.matkul_attribute$X8, initContext);
    record(new Sks_PD(this));
    record(new Jadwal_PD(this));
  }

  /*package*/ static final class Sks_PD extends BasePropertyConstraintsDescriptor {
    public Sks_PD(ConstraintsDescriptor container) {
      super(PROPS.sks$WUTf, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8507255052449896863"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue != 0;
    }
  }
  /*package*/ static final class Jadwal_PD extends BasePropertyConstraintsDescriptor {
    public Jadwal_PD(ConstraintsDescriptor container) {
      super(PROPS.jadwal$WV8g, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8507255052449931431"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return propertyValue != null && propertyValue != "";
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept matkul_attribute$X8 = MetaAdapterFactory.getConcept(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106164L, "daun.structure.matkul_attribute");
  }

  private static final class PROPS {
    /*package*/ static final SProperty sks$WUTf = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106164L, 0x13bb48ea8c10616eL, "sks");
    /*package*/ static final SProperty jadwal$WV8g = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106164L, 0x13bb48ea8c10616fL, "jadwal");
  }
}
