package daun.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Program_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Program_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Program$xx, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Program$xx = MetaAdapterFactory.getConcept(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106155L, "daun.structure.Program");
  }
}
