package daun.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SEnumerationLiteral;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class rekap_jumlah_Constraints extends BaseConstraintsDescriptor {
  /*package*/ rekap_jumlah_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.rekap_jumlah$J5, initContext);
    record(new Nama_PD(this));
    record(new Jumlah_PD(this));
    record(new Unit_PD(this));
  }

  /*package*/ static final class Nama_PD extends BasePropertyConstraintsDescriptor {
    public Nama_PD(ConstraintsDescriptor container) {
      super(PROPS.nama$WHyk, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8474920443931460462"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return propertyValue != null && propertyValue != "";
    }
  }
  /*package*/ static final class Jumlah_PD extends BasePropertyConstraintsDescriptor {
    public Jumlah_PD(ConstraintsDescriptor container) {
      super(PROPS.jumlah$WHLl, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8474920443931472051"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue > 0;
    }
  }
  /*package*/ static final class Unit_PD extends BasePropertyConstraintsDescriptor {
    public Unit_PD(ConstraintsDescriptor container) {
      super(PROPS.unit$WI0m, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castEnummember(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8474920443931481249"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, SEnumerationLiteral propertyValue) {
      return propertyValue != null;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept rekap_jumlah$J5 = MetaAdapterFactory.getConcept(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615cL, "daun.structure.rekap_jumlah");
  }

  private static final class PROPS {
    /*package*/ static final SProperty nama$WHyk = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615cL, 0x13bb48ea8c106160L, "nama");
    /*package*/ static final SProperty jumlah$WHLl = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615cL, 0x13bb48ea8c106161L, "jumlah");
    /*package*/ static final SProperty unit$WI0m = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c10615cL, 0x13bb48ea8c106162L, "unit");
  }
}
