package daun.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SEnumerationLiteral;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Status_Data_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Status_Data_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Status_Data$Y6, initContext);
    record(new Nama_PD(this));
    record(new Status_PD(this));
  }

  /*package*/ static final class Nama_PD extends BasePropertyConstraintsDescriptor {
    public Nama_PD(ConstraintsDescriptor container) {
      super(PROPS.nama$WVBg, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8507255052450377038"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return propertyValue != null && propertyValue != "";
    }
  }
  /*package*/ static final class Status_PD extends BasePropertyConstraintsDescriptor {
    public Status_PD(ConstraintsDescriptor container) {
      super(PROPS.status$WVQh, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castEnummember(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4622b345-71d3-4187-85ee-4636b8123d49(daun.constraints)", "8507255052450393130"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, SEnumerationLiteral propertyValue) {
      return propertyValue != null;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Status_Data$Y6 = MetaAdapterFactory.getConcept(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106166L, "daun.structure.Status_Data");
  }

  private static final class PROPS {
    /*package*/ static final SProperty nama$WVBg = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106166L, 0x13bb48ea8c106171L, "nama");
    /*package*/ static final SProperty status$WVQh = MetaAdapterFactory.getProperty(0x26ef42d6083d44d9L, 0x8ed5b8e28497bd10L, 0x13bb48ea8c106166L, 0x13bb48ea8c106172L, "status");
  }
}
